'use client';
import { useState } from 'react';
import Link from 'next/link';
import { ArrowLeft, Upload } from 'lucide-react';
import { Brand } from '../../components/Brand';
import { formations } from '../../lib/formations';
export default function Administration(){
 const [status,setStatus]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(false);
 async function upload(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget;const data=new FormData(form);const token=String(data.get('token'));data.delete('token');setBusy(true);setStatus('');setError(false);try{const result=await fetch('/api/documents',{method:'POST',headers:{Authorization:`Bearer ${token}`},body:data});const body=await result.json();if(!result.ok)throw new Error(body.error||'Le dépôt a échoué.');setStatus('Document publié. Il est maintenant disponible dans la bibliothèque.');form.reset()}catch(e){setError(true);setStatus(e instanceof Error?e.message:'Le dépôt a échoué.')}finally{setBusy(false)}}
 return <><div className="sub-header wrap"><Brand/><Link href="/bibliotheque"><ArrowLeft size={15}/> Bibliothèque</Link></div><main className="wrap upload-wrap"><div className="page-intro"><div className="eyebrow">ESPACE ADMINISTRATION</div><h1>Partager un document.</h1><p>Accès réservé aux personnes habilitées par l’établissement. Les documents publiés sont accessibles à tous les visiteurs : déposez uniquement des ressources pédagogiques destinées au partage public.</p></div><form className="form-card" onSubmit={upload}><label className="field">Clé d’administration *<input type="password" name="token" autoComplete="off" required maxLength={200}/></label><label className="field">Titre du document *<input name="title" required maxLength={140} placeholder="Ex. : Exercices d’électricité — chapitre 1"/></label><div className="field-grid"><label className="field">Formation *<select name="formation" required><option value="TOUS">Toutes les formations</option>{formations.map(f=><option key={f.code} value={f.code}>{f.code} — {f.name}</option>)}</select></label><label className="field">Niveau *<select name="niveau" required><option>Tous niveaux</option><option>Seconde</option><option>Première</option><option>Terminale</option><option>Centre de formation</option></select></label></div><label className="field" style={{marginTop:20}}>Fichier PDF *<input type="file" name="file" accept="application/pdf,.pdf" required/></label><p className="form-note">4 Mo maximum sur Vercel. N’incluez pas de coordonnées d’élèves ni de données confidentielles.</p><button className="button" type="submit" disabled={busy}><Upload size={17}/>{busy?'Publication en cours…':'Publier le document'}</button>{status&&<p role={error?'alert':'status'} className={error?'error':'success'}>{status}</p>}</form></main></>;
}
