'use client';
import { useEffect, useState } from 'react';
import Link from 'next/link';
import { ArrowLeft, BookOpen, Download, FileText } from 'lucide-react';
import { Brand } from '../../components/Brand';
import { formations, whatsapp } from '../../lib/formations';

type Document={id:string;title:string;formation:string;niveau:string;size:number;createdAt:string};
export default function Bibliotheque(){
 const [docs,setDocs]=useState<Document[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(false),[search,setSearch]=useState(''),[formation,setFormation]=useState(''),[niveau,setNiveau]=useState('');
 async function refresh(){setLoading(true);setError(false);try{const response=await fetch('/api/documents');if(!response.ok)throw new Error();setDocs(await response.json());}catch{setError(true)}finally{setLoading(false)}}
 useEffect(()=>{void refresh()},[]);
 const filtered=docs.filter(d=>(!formation||d.formation===formation||d.formation==='TOUS')&&(!niveau||d.niveau===niveau||d.niveau==='Tous niveaux')&&d.title.toLocaleLowerCase('fr').includes(search.toLocaleLowerCase('fr')));
 return <><div className="sub-header wrap"><Brand/><Link href="/"><ArrowLeft size={15}/> Retour à l’accueil</Link></div><main className="wrap library-content"><div className="page-intro"><div className="eyebrow">L’ESPACE DES APPRENANTS</div><h1>Votre bibliothèque.<br/><span>Le savoir à portée de main.</span></h1><p>Supports de cours, exercices et documents utiles : retrouvez les ressources partagées par l’établissement pour votre parcours.</p></div><div className="filters"><label className="field">Rechercher un document<input type="search" placeholder="Titre du document…" value={search} onChange={e=>setSearch(e.target.value)}/></label><label className="field">Formation<select value={formation} onChange={e=>setFormation(e.target.value)}><option value="">Toutes les formations</option>{formations.map(f=><option key={f.code} value={f.code}>{f.code} — {f.name}</option>)}</select></label><label className="field">Niveau<select value={niveau} onChange={e=>setNiveau(e.target.value)}><option value="">Tous les niveaux</option><option>Seconde</option><option>Première</option><option>Terminale</option><option>Centre de formation</option></select></label></div>{loading?<p className="status" role="status">Chargement des documents…</p>:error?<div className="error" role="alert">La bibliothèque est momentanément indisponible. <button className="button small" onClick={refresh}>Réessayer</button></div>:filtered.length?<><p className="status" role="status">{filtered.length} document{filtered.length>1?'s':''}</p><div className="doc-list">{filtered.map(d=><article className="doc" key={d.id}><FileText size={28}/><h3>{d.title}</h3><p>{d.formation==='TOUS'?'Toutes les formations':d.formation} · {d.niveau}</p><p>PDF · {(d.size/1024/1024).toFixed(1)} Mo · {new Date(d.createdAt).toLocaleDateString('fr-FR')}</p><a href={`/api/documents/${d.id}`} download><Download size={16}/> Télécharger le document</a></article>)}</div></>:<div className="empty"><BookOpen size={38}/><h2>{docs.length?'Aucun document ne correspond.':'La bibliothèque se prépare.'}</h2><p>{docs.length?'Essayez une autre recherche ou sélectionnez une autre formation.':'Les documents seront disponibles dès leur publication par l’établissement.'}<br/>Un document en particulier ? Le secrétariat peut vous orienter.</p><a className="button small" href={`${whatsapp}?text=${encodeURIComponent('Bonjour, je recherche un document pour ma formation. Pouvez-vous m’aider ?')}`} target="_blank" rel="noreferrer">Contacter le secrétariat</a></div>}<Link className="admin-link" href="/administration">Espace administration →</Link></main></>;
}
